/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMessage: typeof import('./src/components/end/AsideMessage.vue')['default']
    BackGround: typeof import('./src/components/BackGround.vue')['default']
    CardDetail: typeof import('./src/components/CardDetail.vue')['default']
    FansFollow: typeof import('./src/components/personInfo/FootCommponent/UserMessage/FansFollow.vue')['default']
    FeedBacks: typeof import('./src/components/personInfo/FeedBacks.vue')['default']
    Fix: typeof import('./src/components/end/foot/Fix.vue')['default']
    FootBar: typeof import('./src/components/FootBar.vue')['default']
    FootContent: typeof import('./src/components/personInfo/FootContent.vue')['default']
    FootMessage: typeof import('./src/components/end/FootMessage.vue')['default']
    LikeMessage: typeof import('./src/components/personInfo/FootCommponent/UserMessage/LikeMessage.vue')['default']
    Live2d: typeof import('./src/components/live2d/live2d.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    MainMessage: typeof import('./src/components/end/MainMessage.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NewCard: typeof import('./src/components/NewCard.vue')['default']
    NodeCard: typeof import('./src/components/NodeCard.vue')['default']
    OptionContent: typeof import('./src/components/personInfo/OptionContent.vue')['default']
    Person: typeof import('./src/components/personInfo/person.vue')['default']
    PrButton: typeof import('./src/components/PrButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolSelect: typeof import('./src/components/SchoolSelect.vue')['default']
    Search: typeof import('./src/components/search/search.vue')['default']
    SystemMessage: typeof import('./src/components/personInfo/FootCommponent/UserMessage/SystemMessage.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TopInfo: typeof import('./src/components/personInfo/TopInfo.vue')['default']
    TopTitle: typeof import('./src/components/end/TopTitle.vue')['default']
    UserAuth: typeof import('./src/components/personInfo/FootCommponent/UserAuth.vue')['default']
    UserMessage: typeof import('./src/components/personInfo/FootCommponent/UserMessage.vue')['default']
    UserPostid: typeof import('./src/components/personInfo/FootCommponent/UserPostid.vue')['default']
    UserSetting: typeof import('./src/components/personInfo/FootCommponent/UserSetting.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPagination: typeof import('vant/es')['Pagination']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
